Logout
Arqui-software-grupo03/arqui-frontend pull request #6
Opened 2018-10-24 02:35 UTC by fadelafuente1

2018-10-24 03:12 UTC, stephichau requested changes
La sesión lo verifica el AppComponent; Si no existe el par (email, token) en local storage, el usuario por default es un diccionario vacio ({}). Despues, cuando hace login correctamente, se guarda el par (email, token) y se setea el usuario como {email: email, token:token}. Dp , si ingresai denuevo al "home", primero verifica si tiene el email,token en localStorage en AppComponent. No es necesario que todos los componentes verifiquen si tiene token.

- Logout debería ser otro componente

- al crear un componente, usa: ng g c NombreComponente --spec false

2018-10-24 03:12 UTC, stephichau commented on webApp/src/app/navbar/login/login.component.ts
> +    jQuery('[data-toggle="toolip"]').tooltip({
debería ser "tooltip"

2018-10-24 03:12 UTC, stephichau commented on webApp/src/app/navbar/login/login.component.ts
> +  @Input() isLooged: boolean;
es redundante las variables

2018-10-24 03:12 UTC, stephichau commented on webApp/src/app/navbar/navbar.component.html
> +      <li *ngIf="isLooged" class="nav-item">
Toda esta sección se puede dejar en un *ngIf else ng-template

2018-10-25 17:50 UTC, fadelafuente1 commented on webApp/src/app/navbar/login/login.component.ts
> +    jQuery('[data-toggle="toolip"]').tooltip({
Listo

2018-10-26 14:42 UTC, stephichau approved these changes

2018-10-26 14:42 UTC, merged